### ISSUE TITLE
Some Issues with the Implementation

### ISSUE THREAD

**Issue by gary-harpaz** [RedisLabs/redis-quartz#8]
Here are some of the problems I've experienced with this implementation:
- faulty Redis lock implementation. Unexpected shutdown may cause it hang forever on next restart.
- Unexpected shutdown when a repeating is acquired. The trigger will neve fire again on the next restart.
- Trigger JobDataMap do not persist at all. According to Quartz docs they trigger dta map is supposed to be merged with job data map when trigger value will override the job values.

**Comment by kehati** [comment]
Hi @gary-harpaz .

We recently merged a new locking mechanism, using jedis-locks. Nevertheless, have you configured  the 'releaseTriggersInterval' and 'instanceIdFilePath' to release triggers of non-alive schedulers or previous schedulers on startup?

As for the JobdataMap, the JobDataMap is persisted in an identical manner to other job stores on storeJob- see the RAMJobStore for an example. If you think of a better way of implementing this or you think there are issues with the storeJob method, would you be willing to work on a solution and  contribute it to the community?

Finally, submitting an issue titled "Full of bugs!" and "Stay away!" violates the policy of being nice and respectful to each other which this community highly values, and I ask you to refrain from this attitude in the future.

**Comment by gary-harpaz** [comment]
I did set the 'releaseTriggersInterval' and 'instanceIdFilePath' parameters.
I'm not talking about jobdatamap I'm talking about triggerdatamap. Two different things.
As for my attitude I think that it is justified under this circumstances.  
This repository does not belong to some kid learning a new framework. This is an official RedisLabs repository with 37 stars.
Last commit was two years ago, buggy, using depreached  Jedis functions.
Made me loose an entire work day before returned back  to JDBC store.
Come on! 
Expected better from Redis Labs.

**Comment by kehati** [comment]
1. If you have set up the triggers release mechanisms but still experienced locking issues, please describe in details the steps you took to reproduce these issues. 
2. TriggerDataMaps are not quartz entities- a trigger has a JobDataMap which you can get or set, and they are stored in an identical manner as other JobDataMaps. Again, .If you think of a better way of implementing the job store, you are welcome to share your ideas and submit a pull request.
3. While in here, you are expected to be nice and respectful to anyone, regardless if it is a kid or a reputable company.
   This repository belongs to the community, and you are welcome to use it free of charge and in compliance with its licensing. If you think it is buggy or outdated, by all means do submit a pull request instead of whining about losing a working day.

**Comment by gary-harpaz** [comment]
Thank you for schooling me and teaching me proper netiquette.
Calling your code buggy is not disrespectful, it's just the truth. And my intentions were to spare other innocent coders from wasting their precious time on it.
So you see, in my own way I too am helping the community.
Here's a different thought, instead of taking offense when someone points out the obvious how bout you just fix your code?
Beseder Matan? :)

**Comment by kehati** [comment]
@gary-harpaz, submitting an issue with a title: "Full of bugs. Stay away from this code" and without any constructive info is rude, disrespectful. and unacceptable. 
An issue should be submitted with an informative title that clearly describes the issue, a clear description of the issue, steps to reproduce and a suggested resolution, if you have any.
Any other use is an abuse of our ticketing system, and it is unacceptable.

If you want to "spare other innocent coders from wasting their precious time on it." write a post or something. This is GitHub here, not Facebook.

As you clearly expressed your abusive intentions regarding this issue, I'll go ahead and close it now.
